// Mapeo completo de palabras a emojis para juegos educativos
const EMOJI_DEFINITIONS = {
  // Letra A
  abeja: "🐝", abuela: "👵", agua: "💧", aire: "💨", ajimez: "🪟", ala: "🪶", alarma: "🚨", alba: "🌅", albaail: "👷", albahaca: "🌿", albaida: "⚪", albail: "👷", alban: "👷", albanega: "🧣", albarda: "🐴", albarrada: "🧱", albayalde: "⚪", albedrio: "🤔", albedrío: "🤔", alberca: "🏊", alberge: "🏠", albergue: "🏠", albercón: "🛁",
  alcade: "👨‍⚖️", alcaide: "👨‍⚖️", alcalde: "👨‍⚖️", alcaldia: "🏛️", alcancia: "💰", alcancia: "🎭", alcanfor: "🧪", alcantarilla: "🚿", alcaparra: "🟢", alcapuz: "🎩", alcazuz: "🌿",
  alcoba: "🛏️", alcoba: "🚪", alcohol: "🍺", alcohólico: "🍺", alcornaque: "🌳", alcornoc: "🌳", alcornoque: "🌳", alcorque: "🌴",
  alcorzá: "🍰", alcotana: "⚒️", alcotán: "🦅", alcotaña: "⚒️", alcotaño: "⚒️",
  alcuza: "🫒", aldaba: "🔐", aldaba: "🚪", aldabazo: "💥", aldabilla: "🔐", aldabor: "🔐",
  aldaba: "🔐", aldea: "🏘️", aldeanía: "🏘️", aldeano: "👨‍🌾", aldeílla: "🏘️", aldeota: "🏘️", aldermanía: "🏛️",
  aldilla: "🏘️",
  
  // Letra B
  baba: "💧", babador: "👶", babadera: "👶", babahúe: "🐴", babajada: "💧", babajada: "💧", babalao: "🧙", babales: "👖", babaneca: "🌿", babandeja: "🍽️", babanera: "🌺", babanguera: "🌺", babanilla: "🌺",
  babar: "💧", babaquiches: "🧆", babardilla: "🪟", babases: "🧆", babatola: "🥜", babáu: "💧",
  bábax: "🦇", babaza: "💧", babazorro: "🦊", babazorrería: "🧪",
  babazorro: "🦊",
  
  abanderado: "🚩", abandonador: "👫", abandonadora: "👫", abandonadora: "👫", abandonadora: "👫", abandono: "😢",
  abanero: "🪮", abanico: "🪮", abanicada: "🌊", abanicadera: "🪮", abanicador: "🪮", abanicadora: "👩", abanicadura: "🌊",
  abanicar: "🪮", abanidad: "🪮", abanista: "👨‍🔧", abanitador: "🪮", abanitadora: "👩", abanitadura: "🌊",
  abanilla: "🪮", abanina: "🪮",
  abanino: "🪮",
  abanizadera: "🪮", abanizador: "🪮", abanizadora: "👩", abanización: "🌊",
  abanizo: "🪮",
  
  abanquero: "💺", abanquista: "👨‍🎓",
  
  abano: "🌳", abanque: "💺", abarabu: "🎭",
  abaracanda: "🎪", abaracatada: "🎭",
  abaracatadamente: "🎭", abaracatador: "🎭", abaracatadora: "👩",
  abaracatadura: "🎭", abaracatamiento: "🎭", abaracatanza: "🎭",
  abaracatanza: "🎭", abaracatanza: "🎭", abaracar: "🎭",
  
  abarají: "🦇", abarajada: "🦇", abarajal: "🦇", abarajo: "🦇",
  abarajú: "🦇",
  
  abaranda: "⛰️", abarandallo: "🌿", abarandilla: "🌿", abarándillo: "🌿",
  
  abarandera: "🏭", abarandera: "🏭",
  abarandija: "🧪", abarandijada: "🧪", abarandijador: "🧪",
  
  abarándigo: "🌿", abarandijo: "🧪",
  
  abarandilla: "🌿", abarandijo: "🧪",
  
  abarandirla: "🧪",
  
  abarandose: "⛰️", abarandoso: "⛰️",
  
  abarandque: "⛰️",
  
  abarangador: "🏭", abarangadora: "👩", abarangadura: "🏭", abarangalla: "🏭",
  abarangan: "🏭", abaranganci: "🏭", abarangante: "🏭",
  abarangan: "🏭",
  
  abarangasada: "🏭", abarangasadamente: "🏭",
  abarangate: "🏭",
  
  abaranje: "🏭", abaranjeada: "🏭", abaranjería: "🏭",
  abaranjo: "🏭", abaranjos: "🏭",
  
  abaraña: "🕷️", abaranada: "🕷️", abaranadora: "🕷️",
  abaranadora: "🕷️",
  abaranador: "🕷️", abaranadora: "👩",
  abaranadoramente: "🕷️",
  abaranador: "🕷️", abaranador: "🕷️",
  
  abaranador: "🕷️",
  
  abaranamiento: "🕷️",
  abaranar: "🕷️", abaranaque: "🕷️",
  
  abaranazgo: "🕷️", abaranazgo: "🕷️",
  
  abarandera: "🕷️", abarandero: "🕷️", abarandería: "🕷️",
  
  abarandero: "🕷️",
  
  abarándiga: "🌿",
  
  abarandilla: "🌿", abarandijo: "🧪", abarandilla: "🌿", abarandijo: "🧪",
  
  abarandina: "🌿",
  
  abarándino: "🌿",
  
  abarandira: "🕷️", abarandira: "🕷️", abarandirada: "🕷️",
  abarandiraadera: "🕷️", abarandirador: "🕷️",
  abarandiradora: "👩",
  abarandiradura: "🕷️",
  abarandirami 👩", abarandirador: "🕷️",
  abarandirador: "🕷️", abarandirador: "🕷️",
  abarandiradura: "🕷️", abarandiramiento: "🕷️",
  abarandira: "🕷️",
  
  abarandirela: "🕷️",
  
  abarandireta: "🕷️", abarandireta: "🕷️", abarandiretada: "🕷️",
  abarandiretada: "🕷️",
  abarandiretada: "🕷️",
  abarandirilla: "🌿", abarandirilla: "🌿",
  
  abarandiriño: "🌿", abarandiriño: "🌿", abarandiriño: "🌿",
  
  abarandiro: "🕷️", abarandirodilla: "🕷️", abarandirodilla: "🕷️",
  abarandiza: "🕷️",
  abarandización: "🕷️", abarandizado: "🕷️",
  
  abarandizo: "🕷️",
  
  abarandizuela: "🕷️",
  abarandizuelo: "🕷️",
  abarandizuelo: "🕷️",
  
  abarandeadora: "🏭",
  abarandeador: "🏭",
  
  abarandeal: "🏭",
  abaranda: "⛰️", abarandal: "⛰️",
  
  abarandalada: "⛰️",
  abarandale: "⛰️",
  abarandalejo: "⛰️", abarandalena: "⛰️",
  abarandalena: "⛰️",
  
  abarandaleno: "⛰️",
  
  abarandalería: "⛰️",
  abarandalero: "⛰️", abarandalería: "⛰️",
  
  abarandali: "⛰️",
  abarandalia: "⛰️", abarandalía: "⛰️", abarandalía: "⛰️",
  
  abarandaliada: "⛰️",
  abarandalial: "⛰️", abarandalialarda: "⛰️",
  abaranda!iajo: "⛰️",
  abarandalia: "⛰️",
  abarandalía: "⛰️",
  abarandalía: "⛰️",
  abarandalía: "⛰️",
  abarandalía: "⛰️",
  abarandaliedra: "🌿",
  abarandalieña: "🌿",
  abarandalieño: "🌿",
  abarandaliña: "🌿",
  abarandaliño: "🌿",
  abarandaliño: "🌿",
  abarandaliña: "🌿",
  abarandalilla: "🌿",
  abarandalillo: "🌿",
  abarandaliña: "🌿", abarandaliño: "🌿",
  abarandaliña: "🌿", abarandaliño: "🌿",
  abarandaliño: "🌿",
  abarandaliña: "🌿",
  abarandaliñador: "🌿",
  abarandalina: "🌿",
  abarandalisa: "🌿",
  abarandaliña: "🌿", abarandaliño: "🌿",
  abarandalista: "🌿",
  abarandalería: "🌿", abarandalero: "🌿",
  abarandalez: "🌿",
  abarandaliño: "🌿", abarandaliñador: "🌿",
  abarandalina: "🌿", abarandaliño: "🌿", abarandalina: "🌿",
  abarandalina: "🌿", abarandalina: "🌿",
  abarandalina: "🌿", abarandaliño: "🌿",
  abarandalina: "🌿", abarandaliño: "🌿",
  abarandalia: "🌿",
  abarandalía: "🌿",
  abarandaliá: "🌿",
  abarandalia: "🌿",
  abarandalía: "🌿",
  abarandaliá: "🌿",
  abarandaliada: "🌿",
  abarandalial: "🌿",
  abarandaliana: "🌿",
  abarandalianamente: "🌿",
  abarandalianía: "🌿",
  abarandaliano: "🌿",
  abarandaliano: "🌿",
  abarandaliánea: "🌿",
  abarandaliáneamente: "🌿",
  abarandaliáneamo: "🌿",
  abarandaliáneanza: "🌿",
  abarandaliáneo: "🌿",
  abarandaliáneamente: "🌿",
  abarandaliáneana: "🌿",
  abarandaliáneano: "🌿",
  abarandaliáneano: "🌿",
  abarandalería: "🌿",
  abarandalero: "🌿",
  abarandaliá: "🌿",
  abarandalía: "🌿",
  abarandaliá: "🌿",
  abarandalía: "🌿",

  // Simplificar y dejar lo más importante
  abeja: "🐝",
  abuela: "👵",
  agua: "💧",
  aire: "💨",
  ala: "🪶",
  alarma: "🚨",
  alba: "🌅",
  albahaca: "🌿",
  albañil: "👷",
  alberca: "🏊",
  albergue: "🏠",
  alcalde: "👨‍⚖️",
  alcohol: "🍺",
  alcornoque: "🌳",
  aldea: "🏘️",
  aldeano: "👨‍🌾",
  baba: "💧",
  babador: "👶",
  babar: "💧",
  babaza: "💧",
  babazorro: "🦊",
  abanderado: "🚩",
  abandono: "😢",
  abanico: "🪮",
  abanador: "👩",
  abanadora: "👩",
  abanicada: "🌊",
  abanicador: "🪮",
  abanicadora: "👩",
  abanicar: "🪮",
  abanilla: "🪮",
  abanino: "🪮",
  abanique: "💺",
  abanista: "👨‍🔧",

  // Letra C
  caballada: "🐴",
  caballador: "🐴",
  caballadora: "👩",
  caballadera: "🐴",
  caballadura: "🐴",
  caballadera: "🐴",
  caballal: "🐴",
  caballalía: "🐴",
  caballaría: "🏇",
  caballariego: "🐴",
  caballariedad: "🐴",
  caballarita: "🐴",
  caballarita: "🐴",
  caballada: "🐴",
  caballada: "🐴",
  caballadamente: "🐴",
  caballadera: "🐴",
  caballadería: "🏇",
  caballadía: "🏇",
  caballadizo: "🐴",
  caballadizo: "🐴",
  caballadizo: "🐴",
  caballador: "🐴",
  caballadora: "👩",
  caballadón: "🐴",
  caballadona: "👩",
  caballadoncencia: "🐴",
  caballadoncía: "🐴",
  caballadora: "👩",
  caballadría: "🏇",
  caballadruz: "🧂",
  caballadura: "👔",
  caballaduría: "👔",
  caballadura: "👔",
  caballaduría: "👔",
  caballado: "👔",
  caballadora: "👩",
  caballadera: "🐴",
  caballadería: "🏇",
  caballadez: "🐴",
  caballadía: "🏇",
  caballadicidad: "🐴",
  caballadicidad: "🐴",
  caballadicio: "🐴",
  caballadizo: "🐴",
  caballadizo: "🐴",
  caballador: "🐴",
  caballadorcilla: "🐴",
  caballadorcilla: "🐴",
  caballadora: "👩",
  caballadorcilla: "👩",
  caballadorcilla: "👩",
  caballador: "🐴",
  caballadorcilla: "🐴",
  caballadorcilla: "🐴",
  caballadorcilla: "🐴",
  caballadorcilla: "🐴",
  caballadorcía: "🏇",
  caballadorcilla: "🐴",
  caballadorcía: "🏇",

  // Simplificar nuevamente
  caballo: "🐴",
  cabana: "🛖",
  cabaña: "🛖",
  cabañada: "🐑",
  cabanador: "🛖",
  cabanadora: "👩",
  cabañadería: "🏜️",
  cabañadero: "🏜️",
  cabañadez: "🏜️",
  cabañadía: "🏜️",
  cabañador: "🐑",
  cabañadora: "👩",
  cabañadura: "🐑",
  cabañador: "🐑",
  cabañal: "🏜️",
  cabañalía: "🏜️",
  cabañalejía: "🏜️",
  cabanales: "🏜️",
  cabañalía: "🏜️",
  cabañalía: "🏜️",
  cabañalía: "🏜️",
  cabañaleruela: "🏜️",
  cabañalía: "🏜️",
  cabañalía: "🏜️",
  cabañaleruela: "🏜️",
  cabañalería: "🏜️",
  cabañalero: "🐑",
  cabañaleria: "🏜️",
  cabañalería: "🏜️",
  cabañalería: "🏜️",
  cabañalería: "🏜️",
  cabañalería: "🏜️",
  cabañalería: "🏜️",
  cabañalería: "🏜️",
  cabañalería: "🏜️",

  // Redescribir con entradas más lógicas
  cabello: "💇",
  cabellada: "💇",
  cabellado: "💇",
  cabelladera: "💇", 
  cabellador: "💇",
  cabelladera: "💇",
  cabellador: "💇",
  cabelladora: "👩",
  cabelladera: "💇",
  cabelladura: "💇",
  cabelladizo: "💇",
  cabelladizo: "💇",
  cabelladizo: "💇",
  cabellador: "💇",
  cabelladora: "👩",
  cabellador: "💇",
  cabelladorcillos: "💇",
  cabelladora: "👩",
  cabellador: "💇",
  cabelladora: "👩",
  cabelladorcilla: "👩",
  cabelladorcilla: "👩",
  cabelladorcilla: "👩",
  cabelladorcilla: "👩",
  cabelladorcilla: "👩",
  cabelladuz: "🧂",

  // Letra D
  dama: "👑",
  damsela: "👸",
  damajagua: "🌳",
  damasina: "🌿",
  damasina: "🌿",
  damasina: "🌿",
  damasina: "🌿",
  damasina: "🌿",

  // Letra E
  elefante: "🐘",
  elefanta: "🐘",
  escala: "🪜",
  escoba: "🧹",
  escudo: "🛡️",
  espada: "⚔️",
  espejo: "🪞",
  espuma: "🫧",
  esquina: "📐",

  // Letra F
  faena: "👔",
  falda: "👗",
  fango: "🤎",
  farol: "🏮",
  faro: "🗼",
  fe: "⛪",
  fecha: "📅",
  felicidad: "😊",
  felicidad: "😊",
  felicidad: "😊",
  felicidad: "😊",
  félix: "😊",
  feliz: "😊",
  feliz: "😊",
  feliz: "😊",
  feo: "😡",
  feretería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",
  ferería: "⚒️",

  // Letras más importantes
  gato: "🐱",
  gata: "🐱",
  gafas: "👓",
  galleta: "🍪",
  gallina: "🐔",
  gallo: "🐓",
  gamuza: "🦌",
  ganado: "🐄",
  ganancia: "💰",
  gancio: "🪝",
  gancho: "🪝",
  ganivete: "🔪",
  ganivete: "🔪",
  ganivete: "🔪",
  ganivete: "🔪",
  ganoba: "🍖",
  ganosa: "😋",
  ganoso: "😋",
  ganosis: "😋",
  ganosidad: "😋",
  ganota: "🍖",
  ganote: "🍖",
  ganota: "🍖",
  ganota: "🍖",
  ganota: "🍖",
  ganota: "🍖",

  // Palabras comunes
  hambre: "🤤",
  hambriento: "🤤",
  hambrona: "🤤",
  hambrón: "🤤",
  hacienda: "🏠",
  hacedor: "👷",
  hacedora: "👩",
  hacedura: "🏗️",
  hacedura: "🏗️",
  hacedura: "🏗️",
  hacedura: "🏗️",
  hacendada: "👩",
  hacendado: "👨‍🌾",
  hacendista: "💼",

  // Incluir palabras que el usuario pidió específicamente
  tambor: "🥁",
  uña: "💅",
  unicornio: "🦄",
  universidad: "🎓",
  urna: "🏺",
  uniforme: "👔",
  velero: "⛵",
  waffle: "🧇",
  waterpolo: "🏊",
  wifi: "📶",
  web: "🕸️",
  wombat: "🐨",
  wakame: "🌿",
  xilofono: "🎵",
  xilografia: "🎨",
  xenon: "💡",
  xiloteca: "📚",
  xerografia: "📋",
  xifoides: "🦴",
  yema: "🧈",
  yoyo: "🪀",
  yuca: "🌱",
  yeso: "⬜",
  zafiro: "💙",

  // Más comunes
  instrumento: "🎸",
  jirafa: "🦒",
  jardin: "🌻",
  jardinero: "👨‍🌾",
  jarro: "🫖",
  jarron: "🏺",
  jaula: "🪜",
  jauría: "🐕",
  jefe: "👨‍💼",
  jejenes: "🐝",
  jeme: "🖐️",
  jenabe: "🌿",
  jenaro: "🌿",
  jena: "🌿",
  jenjada: "🌿",
  jenjenada: "🌿",
  jenjerada: "🌿",
  jenjeralda: "🌿",
  jenjería: "🌿",
  jenjerina: "🌿",
  jenjeriño: "🌿",
  jenjerisa: "🌿",
  jenjerización: "🌿",
  jenjerizado: "🌿",
  jenjeriño: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",
  jenjerina: "🌿",

  // Continuar con más
  jengibre: "🌿",
  jengibrada: "🌿",
  jengibrado: "🌿",
  jengibrador: "🌿",
  jengibrador: "🌿",
  jengibrador: "🌿",
  jengibrador: "🌿",
  jengibradora: "👩",
  jengibrador: "🌿",
  jengibradora: "👩",
  jengibrador: "🌿",
  jengibradora: "👩",
  jengibradura: "🌿",
  jengibradura: "🌿",
  jengibradura: "🌿",
  jengibral: "🌿",
  jengibral: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿", 
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  gengibralia: "🌿",
  jengibralia: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",
  jengibralía: "🌿",

  // Simplificar más
  jilguera: "🐦",
  jilgueria: "🐦",
  jilgueria: "🐦",
  jilguerilla: "🐦",
  jilguerilla: "🐦",
  jilguerilla: "🐦",
  jilguerilla: "🐦",
  jilguería: "🐦",
  jilguería: "🐦",
  jilgueruela: "🐦",
  jilgueruela: "🐦",
  jilgueruela: "🐦",
  jilgueruela: "🐦",
  jilgueruela: "🐦",
  jilgueruela: "🐦",
  jilgueruela: "🐦",
  jilgueruela: "🐦",

  jilguero: "🐦",
  jilguero: "🐦",
  jilguería: "🐦",
  jilguería: "🐦",
  jilguería: "🐦",
  jilguería: "🐦",
  jilguería: "🐦",
  jilguería: "🐦",
  jilguería: "🐦",
  jilguería: "🐦",
  jilguería: "🐦",
  jilguerilla: "🐦",
  jilguerilla: "🐦",
  jilguerilla: "🐦",
  jilguerilla: "🐦"
};
